name: Build and Release Binary

on:
  push:
    tags:
      - "v*.*.*" # Triggers workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.8" # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build binary
      run: pyinstaller gdrive.py

    - name: Get release version
      id: get_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Create zip archive
      run: zip -r dist/gdrive-${{ env.RELEASE_VERSION }}.zip dist/gdrive

    - name: Create Release
      id: create_release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@main
      env:
        GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/gdrive-${{ env.RELEASE_VERSION }}.zip
        asset_name: gdrive-${{ env.RELEASE_VERSION }}.zip
        asset_content_type: application/zip
